let level1;

/*
* Initializes a game level with specified game objects and background elements.
*/
function setLevel() {
    level1 = new Level(
        [
            new Endboss(),
            new Chicken(),
            new ChickenSmall(),
            new Chicken(),
            new ChickenSmall(),
            new Chicken(),
            new ChickenSmall(),
            new Chicken(),
            new ChickenSmall(),
            new Chicken(),
            new ChickenSmall(),
            new Chicken(),
            new ChickenSmall(),
            new Chicken(),
            new ChickenSmall(),
            new Chicken(),
            new ChickenSmall(),
        ],
        [
            new Cloud(100),
            new Cloud(700),
            new Cloud(1200),
            new Cloud(1800),
            new Cloud(2400),
            new Cloud(3000),
            new Cloud(3600),
            new Cloud(4200),
            new Cloud(4800),
        ],
        [
            new BackgroundObject('img/5_background/layers/air.png', - 719),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', - 719),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', - 719),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', - 719),

            new BackgroundObject('img/5_background/layers/air.png', 0),
            new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
            new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
            new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
            new BackgroundObject('img/5_background/layers/air.png', 719),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719),

            new BackgroundObject('img/5_background/layers/air.png', 719 * 2),
            new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 * 2),
            new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 * 2),
            new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 * 2),
            new BackgroundObject('img/5_background/layers/air.png', 719 * 3),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719 * 3),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719 * 3),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719 * 3),

            new BackgroundObject('img/5_background/layers/air.png', 719 * 4),
            new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 * 4),
            new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 * 4),
            new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 * 4),
            new BackgroundObject('img/5_background/layers/air.png', 719 * 5),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719 * 5),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719 * 5),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719 * 5),

            new BackgroundObject('img/5_background/layers/air.png', 719 * 6),
            new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 * 6),
            new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 * 6),
            new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 * 6),
            new BackgroundObject('img/5_background/layers/air.png', 719 * 7),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719 * 7),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719 * 7),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719 * 7),

        ],
        [
            new Coin(360, 200),
            new Coin(400, 200),
            new Coin(400, 160),
            new Coin(620, 180),
            new Coin(620, 140),
            new Coin(680, 120),
            new Coin(720, 80),
            new Coin(760, 60),
            new Coin(800, 60),
            new Coin(840, 80),
            new Coin(880, 100),
            new Coin(1000, 120),
            new Coin(1200, 140),
            new Coin(1280, 180),
            new Coin(1320, 180),
            new Coin(1380, 200),
            new Coin(1420, 220),
            new Coin(1460, 220),
            new Coin(1500, 160),
            new Coin(1560, 120),
            new Coin(1700, 160),
            new Coin(1800, 200),
            new Coin(1840, 160),
            new Coin(1840, 120),
            new Coin(1900, 200),
            new Coin(1950, 190),
            new Coin(2000, 210),
            new Coin(2050, 240),
            new Coin(2100, 200),
            new Coin(2140, 160),
            new Coin(2250, 200),
            new Coin(2300, 240),
            new Coin(2450, 160),
            new Coin(2620, 200),
            new Coin(2800, 200),
            new Coin(2850, 160),
            new Coin(2850, 120),
            new Coin(3050, 225),
            new Coin(3100, 160),
            new Coin(3150, 180),
            new Coin(3200, 180),
            new Coin(3350, 200),
            new Coin(3350, 170),
        ],
        [
            new Bottle(250),
            new Bottle(580),
            new Bottle(810),
            new Bottle(1050),
            new Bottle(1350),
            new Bottle(1650),
            new Bottle(1870),
            new Bottle(2290),
            new Bottle(2800),
        ]
    );
}
